InseeFrLab/onyxia-web

src/js/components/mes-fichiers/mes-fichiers.component.js, src/js/components/mes-fichiers/mes-fichiers.scss
It improves for buckets' lists' style in My Files section.
=> Improved style of buckets in MyFiles

src/index.js, src/js/components/my-lab/nouveau-service/nouveau-service.js, src/js/utils/axios-config.js
* Fix service configuration form
* Adapt to new API (universe) format
=> Fix service form

src/js/utils/form-field.js
=> change visible to hidden

nginx-onyxia-js.conf
=> fix 47 nocache on env-config.js

src/js/configuration/index.js
Fix missing config variable which makes secrets unavailable
=> fix kv secret engine

package-lock.json, package.json, src/js/components/commons/chronometer/index.js, src/js/components/commons/nav-bar/nav-bar.js, src/js/components/commons/service-liste/carte-mon-service.tsx, src/js/components/mes-fichiers/navigation/my-file/details.component.js, src/js/components/mes-fichiers/navigation/my-file/my-file.component.js, src/js/components/mon-compte/mon-compte.component.js, src/js/components/mon-compte/mon-compte.component.tsx, src/js/components/mon-compte/s3.tsx, src/js/configuration/betatest.ts, src/js/i18n/dictionary/moncompte.js, src/js/model/User.ts, src/js/model/index.ts, src/js/model/sampledata/basic-user.json, src/js/utils/state-tasks.js
mon compte is now in typescript and a functional component
moment dependency has been removed and replaced by dayjs
=> Refactor mon compte

.gitignore, src/js/api/configuration.ts, src/js/api/my-lab.ts, src/js/components/commons/footer/footer.tsx, src/js/configuration/api-paths.ts, src/js/model/CloudshellConfiguration.ts, src/js/model/Region.ts, src/js/utils/axios-config.js
Goal is to read configuration from API to get version info, available regions and possibly more :)  
This is a first step towards more configuration options, region selection and more.
=> Get api configuration

public/accueil.json, src/js/components/accueil/accueil.component.js, src/js/components/accueil/accueil.scss
I've tried to update the main parts of the layout following the new design system.
Here's a screenshot 
This is the first time I work with React: I'm not familiar with the styling best practices with this framework. 
I'm sure this PR can be improved.
=> Some layout implementations

src/js/env.ts
=> Fix type error in env

src/js/components/mes-fichiers/navigation/NavigationFile.tsx, src/js/redux/myFiles.ts
Also feat retrocompat with the older version
=> Feat compat with newer minio versions

src/js/components/my-lab/catalogue/catalogue-navigation/leaf/deploiement/nouveau-service.tsx
=> support dots in field names #193

src/js/components/my-lab/catalogue/catalogue-navigation/leaf/deploiement/custom-service/component.tsx, src/js/components/my-lab/catalogue/catalogue-navigation/leaf/deploiement/nouveau-service.tsx
I forgot to submit the PR @fcomte
=> Support number and boolean in contracts #195

src/js/components/my-lab/catalogue/catalogue-navigation/leaf/deploiement/nouveau-service.tsx
=> Workaround for lookback regexp not supported by Safari

src/app/components/pages/MySecrets/MySecrets.tsx
Issue is: https://github.com/InseeFrLab/onyxia-web/issues/247
=> MySecrets, correcting link to documentation

nginx.conf
=> Change the onyxia-web image to listen on both ports 80 and 8080

Dockerfile, nginx.conf, package.json
Fixes: #271
:warning: https://github.com/InseeFrLab/helm-charts/pull/26 should be merged before.
=> Run as non-root

.env.local.sample-insee
Add a tab usecase description (SSP Cloud for this instance)
=> Add a HEADER_USECASE_DESCRIPTION env

src/js/components/commons/Ligne.tsx, src/js/components/mes-fichiers/MyBuckets.tsx, src/js/components/mes-fichiers/navigation/my-file/toolbar.component.js, src/js/components/mes-fichiers/navigation/my-files/toolbar.component.tsx
Should resolve icon fab for:
* folder and description icon on listing files
* Monitoring equalizer on buckets listing.
* Download delete and make partnership link.
=> adding icon on folder ui

src/core/usecases/catalogExplorer.ts, src/stories/pages/Catalog/CatalogExplorer/CatalogExplorerCards/CatalogExplorerCards.stories.tsx, src/ui/components/pages/Catalog/CatalogExplorer/CatalogExplorer.tsx, src/ui/components/pages/Catalog/CatalogExplorer/CatalogExplorerCards/CatalogExplorerCards.tsx
=> Search packages in all catalogs

src/core/usecases/restorablePackageConfigs.ts
=> fix bug "saved config can broke UI"

src/ui/i18n.tsx
Bonjour, 
A défaut d'être suffisamment geek pour faire d'autres contributions à ce jour, voici donc une PR à la hauteur de mes compétences. 
Salutations à la super équipe de développeurs de la DIIT. 
Kim
=> Typos i18n.tsx

.env, .env.local.sample-etalab, .env.local.sample-insee, src/core/ports/OnyxiaApiClient.ts, src/core/setup.ts, src/core/usecases/catalogExplorer.ts, src/ui/env.ts
=> 359 highlighted charts

src/core/ports/OnyxiaApiClient.ts, src/core/secondaryAdapters/mockOnyxiaApiClient.ts, src/core/secondaryAdapters/officialOnyxiaApiClient.ts, src/core/usecases/launcher.ts
=> Add ingressclassname

src/core/usecases/catalogExplorer.ts
=> exact match for highlighted charts in stead of a prefix match

.gitignore, package.json, src/core/adapters/officialOnyxiaApiClient.ts, src/core/ports/OnyxiaApiClient.ts, src/core/usecases/catalogExplorer.ts, src/core/usecases/launcher.ts, src/core/usecases/restorablePackageConfigs.ts, src/core/usecases/runningService.ts, yarn.lock
=> Versions chart
